instancePaths:

instanceFolder: "instances"

modelType: "Continuous" # "Discrete" or "Continuous"

checkPointTimes:
  - 30
  - 60
  - 120
  - 300
  - 600
  - 900
  - 1800
  - 3600
  - 7200

outputDirectory: "outputAfterReview/outputMip/continuous"
