instancePaths:
  - "instances/1.json"
  - "instances/2.json"
  - "instances/3.json"
  - "instances/4.json"
  - "instances/5.json"
  - "instances/6.json"
  - "instances/7.json"
  - "instances/8.json"
  - "instances/9.json"
  - "instances/10.json"

modelType: "Continuous" # "Discrete" or "Continuous"

checkPointTimes:
  - 30
  - 60
  - 120
  - 300
  - 600
  - 900
  - 1800
  - 3600
  - 7200

outputDirectory: "outputNew/outputMip/continuous"
